! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use fallible_member_test, only: &
                fallible_member_fallible_member => &
                    test_fallible_member
        use fallible_object_test, only: &
                fallible_object_fallible_object => &
                    test_fallible_object
        use fallible_string_test, only: &
                fallible_string_fallible_string => &
                    test_fallible_string
        use json_test, only: &
                json_json => &
                    test_json
        use parse_json_test, only: &
                parse_json_parse_json => &
                    test_parse_json
        use veggies, only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(5)

        individual_tests(1) = fallible_member_fallible_member()
        individual_tests(2) = fallible_object_fallible_object()
        individual_tests(3) = fallible_string_fallible_string()
        individual_tests(4) = json_json()
        individual_tests(5) = parse_json_parse_json()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
