name = "rojff"
version = "0.1.0"
license = "MIT"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "Copyright 2021, Brad Richardson"

[dependencies]
erloff = { git = "https://gitlab.com/everythingfunctional/erloff.git", tag = "v2.1.0" }
iso_varying_string = { git = "https://gitlab.com/everythingfunctional/iso_varying_string", tag = "v2.1.0" }
strff = { git = "https://gitlab.com/everythingfunctional/strff", tag = "v2.1.0" }

[dev-dependencies]
vegetables = { git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.2.2" }

[[example]]
name="compactor"
source-dir="example/compactor"
main="main.f90"

[[example]]
name="expander"
source-dir="example/expander"
main="main.f90"
